(()=>{"use strict";
const CT_URL="https://upload.wikimedia.org/wikipedia/commons/b/b5/Pleurakarzinose_bei_Mamma-Karzinom_50W_-_CT_axial_KM_-_001.jpg";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d",{willReadFrequently:true});
const W=canvas.width,H=canvas.height,canvasWrap=document.getElementById("canvasWrap"),doctorToolbar=document.getElementById("doctorToolbar"),nursePanel=document.getElementById("nursePanel");
const image=new Image();image.crossOrigin="anonymous";image.src=CT_URL;
const DEFAULT_STRUCTURES=[
 {key:"target",label:"Tumor",color:"#ff6f91",kind:"target",shapes:[{type:"ellipse",x:.84,y:.22,rx:.075,ry:.075}]},
 {key:"heart",label:"Corazón",color:"#ffd166",shapes:[{type:"ellipse",x:.59,y:.48,rx:.11,ry:.15}]},
 {key:"lungL",label:"Pulmón izquierdo",color:"#68dcff",shapes:[{type:"ellipse",x:.70,y:.46,rx:.18,ry:.27}]},
 {key:"lungR",label:"Pulmón derecho",color:"#6ee7a8",shapes:[{type:"ellipse",x:.30,y:.46,rx:.19,ry:.28}]},
 {key:"breastR",label:"Mama derecha",color:"#c49bff",shapes:[{type:"ellipse",x:.15,y:.24,rx:.11,ry:.13}]},
 {key:"cord",label:"Médula espinal",color:"#ff9f68",shapes:[{type:"circle",x:.50,y:.72,r:.035}]}
];
const clone=v=>JSON.parse(JSON.stringify(v));
let structures=clone(DEFAULT_STRUCTURES);
const toxicities=[
 {q:"Eritema leve y sensibilidad cutánea, sin descamación húmeda.",answer:1},
 {q:"Descamación húmeda limitada a un pliegue, con dolor controlable y necesidad de curaciones locales.",answer:2},
 {q:"Fatiga moderada que limita algunas actividades habituales, pero mantiene el autocuidado.",answer:2}
];
let imgRect={x:85,y:170,w:730,h:565},selectedKey="target",role="doctor",teacher=false,showTruth=false,toolMode="paint",teacherCreds=null;
let layers={},scores={},done={},drawing=false,lastPoint=null,beams=[],dragBeam=-1,lastPlan=null,nurseAnswers=[];
let sessionMode="pending",sessionCode="",lastSessionVersion=null,pollTimer=null;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function normalizeCode(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,16)}
function resetValidationKeepDrawings(){for(const st of structures){scores[st.key]=null;done[st.key]=false}lastPlan=null}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2500)}
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
function S(k){return structures.find(s=>s.key===k)}function complete(){return structures.every(s=>done[s.key])}function physicsUnlocked(){return complete()}function nurseUnlocked(){return !!lastPlan}
function normalizeCode(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,16)}
function resetValidation(){for(const st of structures){scores[st.key]=null;done[st.key]=false}lastPlan=null}
function ensureLayers(){for(const st of structures){if(!layers[st.key]){const c=document.createElement("canvas");c.width=W;c.height=H;layers[st.key]=c}if(!(st.key in scores))scores[st.key]=null;if(!(st.key in done))done[st.key]=false}}
function initLayers(){layers={};scores={};done={};structures.forEach(st=>{const c=document.createElement("canvas");c.width=W;c.height=H;layers[st.key]=c;scores[st.key]=null;done[st.key]=false})}initLayers();
function ensureLayers(){for(const st of structures){if(!layers[st.key]){const c=document.createElement("canvas");c.width=W;c.height=H;layers[st.key]=c}if(!(st.key in scores))scores[st.key]=null;if(!(st.key in done))done[st.key]=false}}
function updateImgRect(){if(!image.width)return;const maxW=790,maxH=585,scale=Math.min(maxW/image.width,maxH/image.height);imgRect.w=image.width*scale;imgRect.h=image.height*scale;imgRect.x=(W-imgRect.w)/2;imgRect.y=170}
image.onload=()=>{updateImgRect();draw()};image.onerror=()=>toast("No pude cargar la CT. Revisa la conexión a internet.");
function shapePx(sh){if(sh.type==="circle")return{type:"circle",x:imgRect.x+sh.x*imgRect.w,y:imgRect.y+sh.y*imgRect.h,r:sh.r*imgRect.w};return{type:"ellipse",x:imgRect.x+sh.x*imgRect.w,y:imgRect.y+sh.y*imgRect.h,rx:sh.rx*imgRect.w,ry:sh.ry*imgRect.h}}
function inShape(x,y,sh){const p=shapePx(sh);return p.type==="circle"?Math.hypot(x-p.x,y-p.y)<=p.r:((x-p.x)/p.rx)**2+((y-p.y)/p.ry)**2<=1}
const maskBytesCache=new Map(),maskBoundaryCache=new Map(),maskCanvasCache=new Map(),maskCentroidCache=new Map();
function b64ToBytes(b64){if(maskBytesCache.has(b64))return maskBytesCache.get(b64);const bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);maskBytesCache.set(b64,out);return out}
function bytesToB64(bytes){let bin="";for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(bin)}
function maskHas(mask,mx,my){if(!mask||mx<0||my<0||mx>=mask.w||my>=mask.h)return false;const i=my*mask.w+mx,b=b64ToBytes(mask.b64);return !!(b[i>>3]&(1<<(i&7)))}
function maskAt(mask,x,y){const mx=Math.floor(x/W*mask.w),my=Math.floor(y/H*mask.h);return maskHas(mask,mx,my)}
function inStruct(st,x,y){return st.referenceMask?maskAt(st.referenceMask,x,y):st.shapes.some(sh=>inShape(x,y,sh))}
function maskCentroid(mask){if(maskCentroidCache.has(mask.b64))return maskCentroidCache.get(mask.b64);let sx=0,sy=0,n=0;for(let y=0;y<mask.h;y++)for(let x=0;x<mask.w;x++)if(maskHas(mask,x,y)){sx+=(x+.5)*W/mask.w;sy+=(y+.5)*H/mask.h;n++}const out=n?{x:sx/n,y:sy/n}:{x:W/2,y:H/2};maskCentroidCache.set(mask.b64,out);return out}
function centroid(st){if(st.referenceMask)return maskCentroid(st.referenceMask);const p=st.shapes.map(shapePx);return{x:p.reduce((x,q)=>x+q.x,0)/p.length,y:p.reduce((y,q)=>y+q.y,0)/p.length}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawBase(){ctx.clearRect(0,0,W,H);const bg=ctx.createRadialGradient(W/2,H/2,60,W/2,H/2,650);bg.addColorStop(0,"#172032");bg.addColorStop(1,"#050b13");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);if(image.width){ctx.drawImage(image,imgRect.x,imgRect.y,imgRect.w,imgRect.h)}
 ctx.save();ctx.font="900 23px system-ui";ctx.fillStyle="rgba(255,255,255,.9)";ctx.textBaseline="middle";ctx.textAlign="left";ctx.fillText("R",imgRect.x-30,imgRect.y+imgRect.h/2);ctx.textAlign="right";ctx.fillText("L",imgRect.x+imgRect.w+30,imgRect.y+imgRect.h/2);ctx.font="700 11px system-ui";ctx.textAlign="center";ctx.fillStyle="rgba(255,255,255,.55)";ctx.fillText("orientación radiológica",W/2,imgRect.y-24);ctx.restore();
 const t=shapePx(S("target").shapes[0]);ctx.save();ctx.fillStyle="rgba(245,245,245,.30)";ctx.strokeStyle="rgba(255,255,255,.22)";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t.x,t.y,t.rx*.42,t.ry*.42,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function drawShapePath(sh){const p=shapePx(sh);ctx.beginPath();p.type==="circle"?ctx.arc(p.x,p.y,p.r,0,Math.PI*2):ctx.ellipse(p.x,p.y,p.rx,p.ry,0,0,Math.PI*2)}
function maskTintCanvas(st){const mask=st.referenceMask,key=st.color+"|"+mask.b64;if(maskCanvasCache.has(key))return maskCanvasCache.get(key);const c=document.createElement("canvas");c.width=mask.w;c.height=mask.h;const g=c.getContext("2d"),im=g.createImageData(mask.w,mask.h),n=parseInt(st.color.slice(1),16),r=(n>>16)&255,gg=(n>>8)&255,b=n&255;for(let y=0;y<mask.h;y++)for(let x=0;x<mask.w;x++)if(maskHas(mask,x,y)){const i=(y*mask.w+x)*4;im.data[i]=r;im.data[i+1]=gg;im.data[i+2]=b;im.data[i+3]=100}g.putImageData(im,0,0);maskCanvasCache.set(key,c);return c}
function maskBoundary(mask){if(maskBoundaryCache.has(mask.b64))return maskBoundaryCache.get(mask.b64);const pts=[];for(let y=1;y<mask.h-1;y++)for(let x=1;x<mask.w-1;x++){if(!maskHas(mask,x,y))continue;if(!maskHas(mask,x-1,y)||!maskHas(mask,x+1,y)||!maskHas(mask,x,y-1)||!maskHas(mask,x,y+1))pts.push({x:(x+.5)*W/mask.w,y:(y+.5)*H/mask.h})}maskBoundaryCache.set(mask.b64,pts);return pts}
function drawTruth(){if(!showTruth)return;structures.forEach(st=>{ctx.save();if(st.referenceMask){ctx.globalAlpha=.55;ctx.drawImage(maskTintCanvas(st),0,0,W,H)}else{ctx.fillStyle=rgba(st.color,.08);ctx.strokeStyle=rgba(st.color,.75);ctx.lineWidth=2;st.shapes.forEach(sh=>{drawShapePath(sh);ctx.fill();ctx.stroke()})}ctx.restore()})}
function drawActiveGuide(){if(role!=="doctor")return;const st=S(selectedKey);if(!st)return;ctx.save();ctx.fillStyle=st.color;ctx.strokeStyle=rgba(st.color,.98);ctx.lineWidth=3;ctx.shadowColor=rgba(st.color,.45);ctx.shadowBlur=5;if(st.referenceMask){const pts=maskBoundary(st.referenceMask);ctx.shadowBlur=3;for(let i=0;i<pts.length;i+=2){const p=pts[i];ctx.beginPath();ctx.arc(p.x,p.y,1.8,0,Math.PI*2);ctx.fill()}}else{ctx.fillStyle=rgba(st.color,.035);ctx.setLineDash([8,7]);st.shapes.forEach(sh=>{drawShapePath(sh);ctx.fill();ctx.stroke()})}const c=centroid(st);ctx.setLineDash([]);ctx.shadowBlur=0;ctx.font="800 12px system-ui";ctx.textAlign="center";ctx.fillStyle=st.color;ctx.fillText(st.referenceMask?"referencia de profesora":"objetivo",c.x,c.y-10);ctx.restore()}
function tint(layer,color){const c=document.createElement("canvas");c.width=W;c.height=H;const g=c.getContext("2d");g.drawImage(layer,0,0);g.globalCompositeOperation="source-in";g.fillStyle=color;g.fillRect(0,0,W,H);return c}
function drawContours(){structures.forEach(s=>{ctx.save();ctx.globalAlpha=.46;ctx.drawImage(tint(layers[s.key],s.color),0,0);ctx.restore()})}
function bodyRing(){return{cx:W/2,cy:imgRect.y+imgRect.h/2,rx:imgRect.w/2+35,ry:imgRect.h/2+38}}
function sourceFor(a){const b=bodyRing();return{x:b.cx+Math.cos(a)*b.rx,y:b.cy+Math.sin(a)*b.ry}}
function beamG(a){const s=sourceFor(a),t=centroid(S("target"));let dx=t.x-s.x,dy=t.y-s.y,l=Math.hypot(dx,dy)||1;return{sx:s.x,sy:s.y,ux:dx/l,uy:dy/l}}
function lineDist(x,y,g){const vx=x-g.sx,vy=y-g.sy,t=vx*g.ux+vy*g.uy,qx=g.sx+t*g.ux,qy=g.sy+t*g.uy;return Math.hypot(x-qx,y-qy)}
function doseAt(x,y){let d=0;for(const a of beams){const g=beamG(a),dist=lineDist(x,y,g);d+=Math.exp(-(dist*dist)/(2*28*28))}return d}
function drawDose(){if(role!=="physics"||!beams.length)return;ctx.save();ctx.beginPath();ctx.rect(imgRect.x,imgRect.y,imgRect.w,imgRect.h);ctx.clip();for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=7)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=7){const d=doseAt(x,y);if(d<.1)continue;const n=d/Math.max(1,beams.length*.7),col=n>.75?"255,185,90":n>.48?"172,237,111":"83,232,174";ctx.fillStyle=`rgba(${col},${clamp(.08+d*.10,.08,.45)})`;ctx.fillRect(x,y,8,8)}ctx.restore()}
function drawRingBeams(){if(role!=="physics")return;const b=bodyRing();ctx.save();ctx.strokeStyle="#3b5872";ctx.lineWidth=2;ctx.setLineDash([8,9]);ctx.beginPath();ctx.ellipse(b.cx,b.cy,b.rx,b.ry,0,0,Math.PI*2);ctx.stroke();ctx.restore();beams.forEach((a,i)=>{const g=beamG(a),ex=g.sx+g.ux*1000,ey=g.sy+g.uy*1000,gr=ctx.createLinearGradient(g.sx,g.sy,ex,ey);gr.addColorStop(0,"rgba(105,220,255,.9)");gr.addColorStop(.5,"rgba(105,235,170,.4)");gr.addColorStop(1,"rgba(183,148,255,.06)");ctx.strokeStyle=gr;ctx.lineWidth=14;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(g.sx,g.sy);ctx.lineTo(ex,ey);ctx.stroke();ctx.fillStyle=dragBeam===i?"#254768":"#081624";ctx.strokeStyle=dragBeam===i?"#fff":"#82e8ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(g.sx,g.sy,18,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.font="800 13px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),g.sx,g.sy)});ctx.textAlign="start";ctx.textBaseline="alphabetic"}
function drawHint(){if(role!=="doctor")return;const s=S(selectedKey);ctx.fillStyle="rgba(5,11,20,.84)";roundRect(240,830,420,42,14);ctx.fill();ctx.font="800 16px system-ui";ctx.textAlign="center";ctx.fillStyle=s.color;ctx.fillText((toolMode==="erase"?"Borra con cuidado · ":"Colorea dentro del punteado · ")+s.label,W/2,858);ctx.textAlign="start"}
function draw(){drawBase();drawTruth();drawContours();drawActiveGuide();drawDose();drawRingBeams();drawHint()}
function pt(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function insideImage(p){return p.x>=imgRect.x&&p.x<=imgRect.x+imgRect.w&&p.y>=imgRect.y&&p.y<=imgRect.y+imgRect.h}
function stroke(a,b){const g=layers[selectedKey].getContext("2d");g.save();g.lineWidth=21;g.lineCap="round";g.lineJoin="round";if(toolMode==="erase"){g.globalCompositeOperation="destination-out";g.strokeStyle="#000";g.fillStyle="#000"}else{g.globalCompositeOperation="source-over";g.strokeStyle="#fff";g.fillStyle="#fff"}if(a){g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke()}else{g.beginPath();g.arc(b.x,b.y,10.5,0,Math.PI*2);g.fill()}g.restore();done[selectedKey]=false;scores[selectedKey]=null;lastPlan=null}
function nearestBeam(x,y){let k=-1,d0=1e9;beams.forEach((a,i)=>{const s=sourceFor(a),d=Math.hypot(x-s.x,y-s.y);if(d<d0){d0=d;k=i}});return d0<44?k:-1}
function angleAt(x,y){const b=bodyRing();return Math.atan2((y-b.cy)/b.ry,(x-b.cx)/b.rx)}function onRing(x,y){const b=bodyRing(),n=Math.sqrt(((x-b.cx)/b.rx)**2+((y-b.cy)/b.ry)**2);return n>.8&&n<1.23}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const p=pt(e);if(role==="doctor"){if(!insideImage(p)){toast("Dibuja dentro de la CT.");return}drawing=true;lastPoint=p;stroke(null,p);canvas.setPointerCapture?.(e.pointerId);updateUI();draw();return}if(role==="physics"){if(!physicsUnlocked()){toast("Completa primero los contornos.");return}const n=nearestBeam(p.x,p.y);if(n>=0){dragBeam=n;canvas.setPointerCapture?.(e.pointerId);draw();return}if(onRing(p.x,p.y)){if(beams.length>=5){toast("Ya tienes 5 haces.");return}beams.push(angleAt(p.x,p.y));lastPlan=null;updateUI();draw()}else toast("Toca el aro punteado.")}});
canvas.addEventListener("pointermove",e=>{const p=pt(e);if(role==="doctor"&&drawing){e.preventDefault();if(insideImage(p)){stroke(lastPoint,p);lastPoint=p;draw()}}else if(role==="physics"&&dragBeam>=0){e.preventDefault();beams[dragBeam]=angleAt(p.x,p.y);lastPlan=null;updateUI();draw()}});
function stop(){drawing=false;lastPoint=null;dragBeam=-1;updateUI();draw()}canvas.addEventListener("pointerup",stop);canvas.addEventListener("pointercancel",stop);
function packLayerAsMask(layer){const mw=225,mh=225,tmp=document.createElement("canvas");tmp.width=mw;tmp.height=mh;const g=tmp.getContext("2d");g.imageSmoothingEnabled=false;g.drawImage(layer,0,0,mw,mh);const data=g.getImageData(0,0,mw,mh).data,bytes=new Uint8Array(Math.ceil(mw*mh/8));let count=0;for(let i=0;i<mw*mh;i++){if(data[i*4+3]>25){bytes[i>>3]|=1<<(i&7);count++}}return{mask:{w:mw,h:mh,b64:bytesToB64(bytes)},count}}
function captureReference(){if(!teacher){toast("Activa Modo profesor para guardar referencias.");return}const layer=layers[selectedKey],packed=packLayerAsMask(layer);if(packed.count<25){toast("Primero dibuja el contorno que Caro quiere usar como referencia.");return}const st=S(selectedKey);st.referenceMask=packed.mask;layer.getContext("2d").clearRect(0,0,W,H);scores[selectedKey]=null;done[selectedKey]=false;lastPlan=null;toast("Referencia de "+st.label+" guardada. Repite con los demás volúmenes.");updateUI();draw()}
function loadReferenceForEditing(){if(!teacher){toast("Activa Modo profesor.");return}const st=S(selectedKey);if(!st.referenceMask){toast("Este volumen todavía usa la referencia geométrica stock.");return}const layer=layers[selectedKey],g=layer.getContext("2d");g.clearRect(0,0,W,H);const mask=st.referenceMask,tmp=document.createElement("canvas");tmp.width=mask.w;tmp.height=mask.h;const tg=tmp.getContext("2d"),im=tg.createImageData(mask.w,mask.h);for(let y=0;y<mask.h;y++)for(let x=0;x<mask.w;x++)if(maskHas(mask,x,y)){const i=(y*mask.w+x)*4;im.data[i]=255;im.data[i+1]=255;im.data[i+2]=255;im.data[i+3]=255}tg.putImageData(im,0,0);g.imageSmoothingEnabled=false;g.drawImage(tmp,0,0,W,H);toolMode="paint";toast("Referencia cargada al pincel. Corrige con Pintar/Borrar y vuelve a guardarla.");updateUI();draw()}
function validate(){const st=S(selectedKey),data=layers[selectedKey].getContext("2d").getImageData(0,0,W,H).data;let pred=0,truth=0,inter=0;for(let y=Math.floor(imgRect.y);y<imgRect.y+imgRect.h;y+=4)for(let x=Math.floor(imgRect.x);x<imgRect.x+imgRect.w;x+=4){const p=data[(y*W+x)*4+3]>20,t=inStruct(st,x,y);if(p)pred++;if(t)truth++;if(p&&t)inter++}const dice=(pred+truth)?2*inter/(pred+truth):0,precision=pred?inter/pred:0,recall=truth?inter/truth:0;scores[selectedKey]={dice,precision,recall};const pass=dice>=.62&&precision>=.78&&recall>=.64;done[selectedKey]=pass;if(pass)toast("¡Muy bien! Coincidencia "+Math.round(dice*100)+"% y buen control del borde.");else if(precision<.78)toast("Te saliste de la guía. Usa Borrar para limpiar lo que quedó fuera.");else if(recall<.64)toast("Falta colorear más del volumen dentro del punteado.");else toast("Casi. Corrige un poco el borde y vuelve a validar.");if(complete()){role="physics";toast("¡Contorneo completo! Física médica desbloqueada.")}updateUI();draw()}
function clearContour(){layers[selectedKey].getContext("2d").clearRect(0,0,W,H);done[selectedKey]=false;scores[selectedKey]=null;lastPlan=null;updateUI();draw()}
function meanDose(s){let t=0,n=0;for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=11)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=11)if(inStruct(s,x,y)){t+=doseAt(x,y);n++}return n?t/n:0}
function healthyDose(){let t=0,n=0;for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=17)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=17){if(structures.some(s=>inStruct(s,x,y)))continue;t+=doseAt(x,y);n++}return n?t/n:0}
function spread(){if(beams.length<2)return 0;const p=beams.slice().sort((a,b)=>a-b),g=[];for(let i=0;i<p.length;i++){const nx=i===p.length-1?p[0]+Math.PI*2:p[i+1];g.push(nx-p[i])}return clamp((Math.PI*1.35-Math.max(...g))/(Math.PI*.7),0,1)}
function evalPlan(){if(beams.length<3){toast("Necesitas al menos 3 haces.");return}const td=meanDose(S("target")),oars=structures.slice(1).map(s=>({label:s.label,dose:meanDose(s)})),healthy=healthyDose(),coverage=clamp(td/Math.max(1.7,beams.length*.56)*100,0,100),avg=oars.reduce((a,b)=>a+b.dose,0)/oars.length,score=Math.round(clamp(coverage-Math.max(0,avg-.45)*30-Math.max(0,healthy-.30)*18+spread()*9,0,100));lastPlan={coverage,oars,healthy,score};role="nurse";renderNurse();updateUI();draw();toast("Plan evaluado. Enfermería desbloqueada.")}
function renderNurse(){const list=document.getElementById("toxicityList");list.innerHTML="";nurseAnswers=Array(toxicities.length).fill(null);toxicities.forEach((q,i)=>{const d=document.createElement("div");d.className="tox-card";d.innerHTML=`<p><b>Situación ${i+1}.</b> ${q.q}</p><div class="tox-options"></div>`;const o=d.querySelector(".tox-options");[0,1,2,3].forEach(g=>{const b=document.createElement("button");b.textContent="Grado "+g;b.onclick=()=>{nurseAnswers[i]=g;[...o.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected")};o.appendChild(b)});list.appendChild(d)});document.getElementById("nurseResult").classList.add("hidden")}
function evalNurse(){if(nurseAnswers.some(v=>v===null)){toast("Responde las tres situaciones.");return}let c=0;nurseAnswers.forEach((v,i)=>{if(v===toxicities[i].answer)c++});const r=document.getElementById("nurseResult");r.classList.remove("hidden");r.innerHTML=`<b>${c}/3 correctas.</b> ${c===3?"Excelente identificación de severidad.":"Revisa qué síntomas indican mayor intervención."}<br><small>Escala educativa simplificada; no sustituye CTCAE ni protocolos institucionales.</small>`;document.getElementById("nurseProgress").textContent=c===3?"Completado ✓":"Evaluado"}
function setRole(r){if(r==="physics"&&!physicsUnlocked()){toast("Completa los seis contornos para entrar a Física.");return}if(r==="nurse"&&!nurseUnlocked()){toast("Enfermería se desbloquea al evaluar el plan.");return}role=r;if(r==="nurse")renderNurse();updateUI();draw()}
function selector(){const w=document.getElementById("structureSelector");w.innerHTML="";structures.forEach(s=>{const b=document.createElement("button");b.className="structure-btn"+(s.key===selectedKey?" active":"")+(done[s.key]?" done":"")+(s.referenceMask?" reference-saved":"");b.style.borderColor=rgba(s.color,.8);b.innerHTML=`<span style="color:${s.color}">●</span> ${s.label}${teacher&&s.referenceMask?" ★":""}`;b.onclick=()=>{selectedKey=s.key;updateUI();draw()};w.appendChild(b)})}
function scoreLabel(sc){if(!sc)return"Pendiente";const pct=Math.round(sc.dice*100);if(sc.precision<.78)return pct+"% · fuera de raya";if(sc.recall<.64)return pct+"% · falta cubrir";return pct+"% · ajustar"}
function renderStatus(){const box=document.getElementById("statusBox");box.innerHTML="";if(role==="doctor"){document.getElementById("missionNum").textContent="1";document.getElementById("missionTitle").textContent="Contorneo médico";document.getElementById("missionText").textContent="Selecciona una estructura, colorea dentro del punteado y usa Borrar para corregir dedazos.";structures.forEach(st=>{const r=document.createElement("div");r.className="status-row";const sc=scores[st.key];r.innerHTML=`<span><i style="color:${st.color}">●</i> ${st.label}</span><b>${done[st.key]?"✓ "+Math.round(sc.dice*100)+"%":scoreLabel(sc)}</b>`;box.appendChild(r)})}else if(role==="physics"){document.getElementById("missionNum").textContent="2";document.getElementById("missionTitle").textContent="Planeación física";document.getElementById("missionText").textContent="Distribuye los haces para cubrir el tumor y reducir dosis a órganos sanos.";box.innerHTML='<div class="status-row"><span>Contornos médicos</span><b>Completos ✓</b></div>'}else{document.getElementById("missionNum").textContent="3";document.getElementById("missionTitle").textContent="Seguimiento de toxicidad";document.getElementById("missionText").textContent="Evalúa síntomas y reconoce cuándo aumenta su severidad.";box.innerHTML='<div class="status-row"><span>Plan</span><b>Evaluado ✓</b></div>'}}
function metrics(){const box=document.getElementById("metrics");box.innerHTML="";if(!lastPlan)return;const vals=[["Cobertura tumor",Math.round(lastPlan.coverage)+"%"],["Tejido sano",lastPlan.healthy.toFixed(2)],...lastPlan.oars.map(o=>[o.label,o.dose.toFixed(2)])];vals.forEach(([a,b])=>{const d=document.createElement("div");d.className="metric";d.innerHTML=`<span>${a}</span><b>${b}</b>`;box.appendChild(d)})}
function renderLiveGuide(){
  const list=document.getElementById("liveSteps"),title=document.getElementById("liveGuideTitle");
  if(!list||!title)return;
  let steps=[];
  if(role==="doctor"){
    title.textContent="1 · Completa los 6 contornos";
    steps=[
      "Elige un volumen arriba de la CT.",
      "Pinta dentro del contorno punteado.",
      "Si te sales, usa Borrar para corregir.",
      "Pulsa Validar contorno hasta obtener ✓.",
      "Repite hasta completar 6/6 y desbloquear Física."
    ];
  }else if(role==="physics"){
    title.textContent="2 · Diseña y evalúa el plan";
    steps=[
      "Toca el aro punteado para colocar 3–5 haces.",
      "Arrastra los círculos numerados para cambiar los ángulos.",
      "Busca cubrir el tumor y evitar los órganos a riesgo.",
      "Pulsa Evaluar plan para obtener tu puntuación y desbloquear Enfermería."
    ];
  }else{
    title.textContent="3 · Evalúa la toxicidad";
    steps=[
      "Lee las tres situaciones clínicas.",
      "Asigna un grado 0–3 a cada una.",
      "Pulsa Evaluar toxicidad para terminar la misión."
    ];
  }
  list.innerHTML=steps.map(x=>"<li>"+x+"</li>").join("");
}
function showHelp(){
  document.querySelectorAll("[data-help-stage]").forEach(el=>el.classList.toggle("current",el.dataset.helpStage===role));
  document.getElementById("helpModal").classList.remove("hidden");
}
function hideHelp(){document.getElementById("helpModal").classList.add("hidden")}
function updateSessionBadge(){const b=document.getElementById("sessionBadge");if(sessionMode==="pending"){b.classList.add("hidden");return}b.classList.remove("hidden");b.textContent=sessionMode==="stock"?"📦 Stock":"🟢 Sesión "+sessionCode}
function updateUI(){document.querySelectorAll(".role-tab").forEach(b=>{const r=b.dataset.role;b.classList.toggle("active",r===role);b.classList.toggle("locked",(r==="physics"&&!physicsUnlocked())||(r==="nurse"&&!nurseUnlocked()))});doctorToolbar.classList.toggle("hidden",role!=="doctor");canvasWrap.classList.toggle("hidden",role==="nurse");nursePanel.classList.toggle("hidden",role!=="nurse");document.getElementById("teacherPanel").classList.toggle("hidden",!teacher);document.getElementById("hudStage").textContent=role==="doctor"?"Doctora · contorneo":role==="physics"?"Física · planeación":"Enfermería · toxicidad";selector();renderStatus();renderLiveGuide();updateSessionBadge();document.getElementById("paintToolBtn").classList.toggle("tool-active",toolMode==="paint");document.getElementById("eraseToolBtn").classList.toggle("tool-active",toolMode==="erase");document.getElementById("doctorProgress").textContent=complete()?"Completado ✓":structures.filter(st=>done[st.key]).length+"/6";document.getElementById("physicsProgress").textContent=!physicsUnlocked()?"Bloqueado":lastPlan?"Completado ✓":"Disponible";if(!nurseUnlocked())document.getElementById("nurseProgress").textContent="Bloqueado";document.getElementById("beamCount").textContent=beams.length+" / 5 haces";const chips=document.getElementById("beamChips");chips.innerHTML="";if(!beams.length){const c=document.createElement("span");c.className="beam-chip";c.textContent="Aún no hay haces";chips.appendChild(c)}else beams.forEach((a,i)=>{const c=document.createElement("span");c.className="beam-chip";c.textContent="Haz "+(i+1)+": "+Math.round((a*180/Math.PI+360)%360)+"°";chips.appendChild(c)});document.getElementById("undoBeamBtn").disabled=!beams.length||!physicsUnlocked();document.getElementById("resetBeamBtn").disabled=!beams.length;document.getElementById("evaluatePlanBtn").disabled=!physicsUnlocked()||beams.length<3;document.getElementById("score").textContent=lastPlan?lastPlan.score:"—";document.getElementById("meterFill").style.width=(lastPlan?lastPlan.score:0)+"%";let g="Completa primero el contorneo.";if(physicsUnlocked())g=beams.length<3?"Coloca al menos 3 haces.":"Listo para evaluar.";if(lastPlan)g=lastPlan.score>=85?"Excelente plan":lastPlan.score>=70?"Buen plan":lastPlan.score>=55?"Plan mejorable":"Replantea los ángulos";document.getElementById("grade").textContent=g;metrics();const pr=document.getElementById("planResult");if(lastPlan){pr.classList.remove("hidden");pr.textContent=lastPlan.score>=85?"Muy buena cobertura con exposición reducida de órganos a riesgo.":lastPlan.score>=70?"Buen equilibrio; todavía puedes proteger mejor algún órgano.":"Prueba ángulos más separados y evita trayectorias que crucen el corazón."}else pr.classList.add("hidden")}

async function fetchSession(code,{silent=false}={}){code=normalizeCode(code);if(!code)return false;try{const r=await fetch("/api/session?code="+encodeURIComponent(code),{cache:"no-store"});if(!r.ok){if(!silent){const d=await r.json().catch(()=>({}));throw new Error(d.error||"No pude cargar la sesión.")}return false}const data=await r.json();if(data.version!==lastSessionVersion){structures=clone(data.structures||DEFAULT_STRUCTURES);ensureLayers();lastSessionVersion=data.version;resetValidationKeepDrawings();selectedKey=structures.some(st=>st.key===selectedKey)?selectedKey:structures[0].key;updateUI();draw();if(silent)toast("El profesor actualizó los contornos de la sesión.")}return true}catch(e){if(!silent)toast(e.message||"Error al conectar.");return false}}
function startPolling(){clearInterval(pollTimer);if(sessionMode!=="session")return;pollTimer=setInterval(()=>fetchSession(sessionCode,{silent:true}),2000)}
async function joinSession(){const code=normalizeCode(document.getElementById("studentSessionCode").value);document.getElementById("studentSessionCode").value=code;if(!code){toast("Escribe un código de sesión.");return}const status=document.getElementById("joinStatus");status.textContent="Conectando…";const ok=await fetchSession(code);if(ok){sessionMode="session";sessionCode=code;document.getElementById("teacherSessionCode").value=code;document.getElementById("startModal").classList.add("hidden");status.textContent="";startPolling();updateUI();draw();toast("Conectada a "+code+". Los contornos se sincronizarán automáticamente.")}else status.textContent="Revisa el código e inténtalo otra vez."}
async function loadCurrentStock(){try{const r=await fetch("/api/stock",{cache:"no-store"});if(r.ok){const d=await r.json();return clone(d.structures||DEFAULT_STRUCTURES)}}catch(e){}return clone(DEFAULT_STRUCTURES)}
async function useStock(){clearInterval(pollTimer);sessionMode="stock";sessionCode="";lastSessionVersion=null;structures=await loadCurrentStock();ensureLayers();resetValidationKeepDrawings();document.getElementById("startModal").classList.add("hidden");updateUI();draw();toast(structures.some(st=>st.referenceMask)?"Usando contornos stock revisados por la profesora.":"Usando contornos stock.");showHelp()}
async function teacherLogin(){const username=document.getElementById("teacherUser").value.trim(),password=document.getElementById("teacherPass").value;try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Credenciales incorrectas.");teacher=true;teacherCreds={username,password};document.getElementById("teacherPass").value="";document.getElementById("teacherModal").classList.add("hidden");if(sessionCode)document.getElementById("teacherSessionCode").value=sessionCode;updateUI();draw();toast("Modo profesor activado.")}catch(e){toast(e.message||"No pude validar el modo profesor.")}}
async function publishSession(){if(!teacherCreds){toast("Vuelve a entrar al modo profesor.");return}const code=normalizeCode(document.getElementById("teacherSessionCode").value);document.getElementById("teacherSessionCode").value=code;if(!code){toast("Escribe un código de sesión, por ejemplo SALON-CURIE01.");return}try{const r=await fetch("/api/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,username:teacherCreds.username,password:teacherCreds.password,structures})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"No pude publicar la sesión.");sessionMode="session";sessionCode=code;lastSessionVersion=d.version;startPolling();updateUI();toast("Sesión "+code+" publicada. Las iPads conectadas se actualizarán en ~2 s.")}catch(e){toast(e.message||"Error al publicar.")}}
async function publishStock(){if(!teacherCreds){toast("Vuelve a entrar al modo profesor.");return}const missing=structures.filter(st=>!st.referenceMask).map(st=>st.label);if(missing.length){toast("Aún faltan referencias dibujadas: "+missing.join(", ")+".");return}if(!confirm("Esto hará que estos 6 contornos sean los nuevos Contornos stock para futuras aperturas. ¿Continuar?"))return;try{const r=await fetch("/api/stock",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:teacherCreds.username,password:teacherCreds.password,structures})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"No pude actualizar el stock.");sessionMode="stock";sessionCode="";updateUI();toast("Stock actualizado. A partir de ahora, nuevas iPads cargarán los contornos de Caro.")}catch(e){toast(e.message||"Error al actualizar el stock.")}}
function teacherEditReset(){resetValidationKeepDrawings();updateUI();draw()}

document.querySelectorAll(".role-tab").forEach(b=>b.onclick=()=>setRole(b.dataset.role));
document.getElementById("paintToolBtn").onclick=()=>{toolMode="paint";updateUI();draw()};
document.getElementById("eraseToolBtn").onclick=()=>{toolMode="erase";updateUI();draw()};
document.getElementById("validateContourBtn").onclick=validate;
document.getElementById("clearContourBtn").onclick=clearContour;
document.getElementById("undoBeamBtn").onclick=()=>{beams.pop();lastPlan=null;updateUI();draw()};
document.getElementById("resetBeamBtn").onclick=()=>{beams=[];lastPlan=null;updateUI();draw();toast("Haces reiniciados.")};
document.getElementById("evaluatePlanBtn").onclick=evalPlan;
document.getElementById("hintBtn").onclick=()=>toast(role==="doctor"?"Sigue el punteado. Si te sales, cambia a Borrar y corrige el borde.":"En mama izquierda suele ser clave vigilar corazón y pulmón ipsilateral.");
document.getElementById("evaluateNurseBtn").onclick=evalNurse;
document.getElementById("useStockBtn").onclick=useStock;
document.getElementById("joinSessionBtn").onclick=joinSession;
document.getElementById("studentSessionCode").addEventListener("keydown",e=>{if(e.key==="Enter")joinSession()});
document.getElementById("teacherBtn").onclick=()=>{if(teacher){teacher=false;teacherCreds=null;showTruth=false;document.getElementById("showTruthChk").checked=false;updateUI();draw();toast("Modo profesor desactivado.")}else document.getElementById("teacherModal").classList.remove("hidden")};
document.getElementById("teacherCancelBtn").onclick=()=>document.getElementById("teacherModal").classList.add("hidden");
document.getElementById("teacherLoginBtn").onclick=teacherLogin;
document.getElementById("showTruthChk").onchange=e=>{showTruth=e.target.checked;draw()};
document.getElementById("publishSessionBtn").onclick=publishSession;
document.getElementById("captureReferenceBtn").onclick=captureReference;
document.getElementById("loadReferenceBtn").onclick=loadReferenceForEditing;
document.getElementById("publishStockBtn").onclick=publishStock;
document.getElementById("helpBtn").onclick=showHelp;
document.getElementById("helpInlineBtn").onclick=showHelp;
document.getElementById("helpCloseBtn").onclick=hideHelp;
document.getElementById("helpCloseX").onclick=hideHelp;
document.getElementById("restoreStockBtn").onclick=async()=>{structures=await loadCurrentStock();selectedKey="target";ensureLayers();teacherEditReset();toast("Referencias stock actuales restauradas.")};
document.querySelectorAll(".shift-btn").forEach(b=>b.onclick=()=>{const st=S(selectedKey);if(st.referenceMask){toast("Esta referencia es un contorno dibujado. Usa Editar referencia dibujada.");return}const dx=parseFloat(b.dataset.dx)/imgRect.w,dy=parseFloat(b.dataset.dy)/imgRect.h;st.shapes.forEach(sh=>{sh.x+=dx;sh.y+=dy});teacherEditReset()});
document.querySelectorAll(".scale-btn").forEach(b=>b.onclick=()=>{const st=S(selectedKey);if(st.referenceMask){toast("Esta referencia es un contorno dibujado. Usa Editar referencia dibujada.");return}const f=parseFloat(b.dataset.scale),cx=st.shapes.reduce((a,x)=>a+x.x,0)/st.shapes.length,cy=st.shapes.reduce((a,x)=>a+x.y,0)/st.shapes.length;st.shapes.forEach(sh=>{sh.x=cx+(sh.x-cx)*f;sh.y=cy+(sh.y-cy)*f;if(sh.type==="circle")sh.r*=f;else{sh.rx*=f;sh.ry*=f}});teacherEditReset()});
updateImgRect();updateUI();draw();
})();