(()=>{"use strict";
const CT_URL="https://upload.wikimedia.org/wikipedia/commons/b/b5/Pleurakarzinose_bei_Mamma-Karzinom_50W_-_CT_axial_KM_-_001.jpg";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d",{willReadFrequently:true});
const W=canvas.width,H=canvas.height,canvasWrap=document.getElementById("canvasWrap"),doctorToolbar=document.getElementById("doctorToolbar"),nursePanel=document.getElementById("nursePanel");
const image=new Image();image.crossOrigin="anonymous";image.src=CT_URL;
const DEFAULT_STRUCTURES=[
 {key:"target",label:"Tumor",color:"#ff6f91",kind:"target",shapes:[{type:"ellipse",x:.84,y:.22,rx:.075,ry:.075}]},
 {key:"heart",label:"Corazón",color:"#ffd166",shapes:[{type:"ellipse",x:.59,y:.48,rx:.11,ry:.15}]},
 {key:"lungL",label:"Pulmón izquierdo",color:"#68dcff",shapes:[{type:"ellipse",x:.70,y:.46,rx:.18,ry:.27}]},
 {key:"lungR",label:"Pulmón derecho",color:"#6ee7a8",shapes:[{type:"ellipse",x:.30,y:.46,rx:.19,ry:.28}]},
 {key:"breastR",label:"Mama derecha",color:"#c49bff",shapes:[{type:"ellipse",x:.15,y:.24,rx:.11,ry:.13}]},
 {key:"cord",label:"Médula espinal",color:"#ff9f68",shapes:[{type:"circle",x:.50,y:.72,r:.035}]}
];
let structures=JSON.parse(JSON.stringify(DEFAULT_STRUCTURES));
const saved=localStorage.getItem("misionRT_breast_truth_v03");if(saved){try{structures=JSON.parse(saved)}catch(e){}}
const toxicities=[
 {q:"Eritema leve y sensibilidad cutánea, sin descamación húmeda.",answer:1},
 {q:"Descamación húmeda limitada a un pliegue, con dolor controlable y necesidad de curaciones locales.",answer:2},
 {q:"Fatiga moderada que limita algunas actividades habituales, pero mantiene el autocuidado.",answer:2}
];
let imgRect={x:85,y:170,w:730,h:565},selectedKey="target",role="doctor",teacher=false,showTruth=false;
let layers={},scores={},done={},drawing=false,lastPoint=null,beams=[],dragBeam=-1,lastPlan=null,nurseAnswers=[];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2500)}
function rgba(hex,a){const n=parseInt(hex.slice(1),16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`}
function S(k){return structures.find(s=>s.key===k)}function complete(){return structures.every(s=>done[s.key])}function physicsUnlocked(){return complete()}function nurseUnlocked(){return !!lastPlan}
function initLayers(){structures.forEach(s=>{const c=document.createElement("canvas");c.width=W;c.height=H;layers[s.key]=c;scores[s.key]=null;done[s.key]=false})}initLayers();
function updateImgRect(){if(!image.width)return;const maxW=790,maxH=585,scale=Math.min(maxW/image.width,maxH/image.height);imgRect.w=image.width*scale;imgRect.h=image.height*scale;imgRect.x=(W-imgRect.w)/2;imgRect.y=170}
image.onload=()=>{updateImgRect();draw()};image.onerror=()=>toast("No pude cargar la CT. Revisa la conexión a internet.");
function shapePx(sh){if(sh.type==="circle")return{type:"circle",x:imgRect.x+sh.x*imgRect.w,y:imgRect.y+sh.y*imgRect.h,r:sh.r*imgRect.w};return{type:"ellipse",x:imgRect.x+sh.x*imgRect.w,y:imgRect.y+sh.y*imgRect.h,rx:sh.rx*imgRect.w,ry:sh.ry*imgRect.h}}
function inShape(x,y,sh){const p=shapePx(sh);return p.type==="circle"?Math.hypot(x-p.x,y-p.y)<=p.r:((x-p.x)/p.rx)**2+((y-p.y)/p.ry)**2<=1}
function inStruct(s,x,y){return s.shapes.some(sh=>inShape(x,y,sh))}
function centroid(s){const p=s.shapes.map(shapePx);return{x:p.reduce((a,b)=>a+b.x,0)/p.length,y:p.reduce((a,b)=>a+b.y,0)/p.length}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function drawBase(){ctx.clearRect(0,0,W,H);const bg=ctx.createRadialGradient(W/2,H/2,60,W/2,H/2,650);bg.addColorStop(0,"#172032");bg.addColorStop(1,"#050b13");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);if(image.width){ctx.drawImage(image,imgRect.x,imgRect.y,imgRect.w,imgRect.h)}
 ctx.save();ctx.font="900 23px system-ui";ctx.fillStyle="rgba(255,255,255,.9)";ctx.textBaseline="middle";ctx.textAlign="left";ctx.fillText("R",imgRect.x-30,imgRect.y+imgRect.h/2);ctx.textAlign="right";ctx.fillText("L",imgRect.x+imgRect.w+30,imgRect.y+imgRect.h/2);ctx.font="700 11px system-ui";ctx.textAlign="center";ctx.fillStyle="rgba(255,255,255,.55)";ctx.fillText("orientación radiológica",W/2,imgRect.y-24);ctx.restore();
 // lesión educativa visible en la mama izquierda (derecha de pantalla)
 const t=shapePx(S("target").shapes[0]);ctx.save();ctx.fillStyle="rgba(245,245,245,.30)";ctx.strokeStyle="rgba(255,255,255,.22)";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(t.x,t.y,t.rx*.42,t.ry*.42,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function drawTruth(){if(!showTruth)return;structures.forEach(s=>{ctx.save();ctx.fillStyle=rgba(s.color,.10);ctx.strokeStyle=rgba(s.color,.95);ctx.lineWidth=3;s.shapes.forEach(sh=>{const p=shapePx(sh);ctx.beginPath();p.type==="circle"?ctx.arc(p.x,p.y,p.r,0,Math.PI*2):ctx.ellipse(p.x,p.y,p.rx,p.ry,0,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore()})}
function tint(layer,color){const c=document.createElement("canvas");c.width=W;c.height=H;const g=c.getContext("2d");g.drawImage(layer,0,0);g.globalCompositeOperation="source-in";g.fillStyle=color;g.fillRect(0,0,W,H);return c}
function drawContours(){structures.forEach(s=>{ctx.save();ctx.globalAlpha=.46;ctx.drawImage(tint(layers[s.key],s.color),0,0);ctx.restore()})}
function bodyRing(){return{cx:W/2,cy:imgRect.y+imgRect.h/2,rx:imgRect.w/2+35,ry:imgRect.h/2+38}}
function sourceFor(a){const b=bodyRing();return{x:b.cx+Math.cos(a)*b.rx,y:b.cy+Math.sin(a)*b.ry}}
function beamG(a){const s=sourceFor(a),t=centroid(S("target"));let dx=t.x-s.x,dy=t.y-s.y,l=Math.hypot(dx,dy)||1;return{sx:s.x,sy:s.y,ux:dx/l,uy:dy/l}}
function lineDist(x,y,g){const vx=x-g.sx,vy=y-g.sy,t=vx*g.ux+vy*g.uy,qx=g.sx+t*g.ux,qy=g.sy+t*g.uy;return Math.hypot(x-qx,y-qy)}
function doseAt(x,y){let d=0;for(const a of beams){const g=beamG(a),dist=lineDist(x,y,g);d+=Math.exp(-(dist*dist)/(2*28*28))}return d}
function drawDose(){if(role!=="physics"||!beams.length)return;ctx.save();ctx.beginPath();ctx.rect(imgRect.x,imgRect.y,imgRect.w,imgRect.h);ctx.clip();for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=7)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=7){const d=doseAt(x,y);if(d<.1)continue;const n=d/Math.max(1,beams.length*.7),col=n>.75?"255,185,90":n>.48?"172,237,111":"83,232,174";ctx.fillStyle=`rgba(${col},${clamp(.08+d*.10,.08,.45)})`;ctx.fillRect(x,y,8,8)}ctx.restore()}
function drawRingBeams(){if(role!=="physics")return;const b=bodyRing();ctx.save();ctx.strokeStyle="#3b5872";ctx.lineWidth=2;ctx.setLineDash([8,9]);ctx.beginPath();ctx.ellipse(b.cx,b.cy,b.rx,b.ry,0,0,Math.PI*2);ctx.stroke();ctx.restore();beams.forEach((a,i)=>{const g=beamG(a),ex=g.sx+g.ux*1000,ey=g.sy+g.uy*1000,gr=ctx.createLinearGradient(g.sx,g.sy,ex,ey);gr.addColorStop(0,"rgba(105,220,255,.9)");gr.addColorStop(.5,"rgba(105,235,170,.4)");gr.addColorStop(1,"rgba(183,148,255,.06)");ctx.strokeStyle=gr;ctx.lineWidth=14;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(g.sx,g.sy);ctx.lineTo(ex,ey);ctx.stroke();ctx.fillStyle=dragBeam===i?"#254768":"#081624";ctx.strokeStyle=dragBeam===i?"#fff":"#82e8ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(g.sx,g.sy,18,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#fff";ctx.font="800 13px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),g.sx,g.sy)});ctx.textAlign="start";ctx.textBaseline="alphabetic"}
function drawHint(){if(role!=="doctor")return;const s=S(selectedKey);ctx.fillStyle="rgba(5,11,20,.84)";roundRect(240,830,420,42,14);ctx.fill();ctx.font="800 16px system-ui";ctx.textAlign="center";ctx.fillStyle=s.color;ctx.fillText("Colorea: "+s.label,W/2,858);ctx.textAlign="start"}
function draw(){drawBase();drawTruth();drawContours();drawDose();drawRingBeams();drawHint()}
function pt(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function insideImage(p){return p.x>=imgRect.x&&p.x<=imgRect.x+imgRect.w&&p.y>=imgRect.y&&p.y<=imgRect.y+imgRect.h}
function stroke(a,b){const g=layers[selectedKey].getContext("2d");g.save();g.strokeStyle="#fff";g.fillStyle="#fff";g.lineWidth=25;g.lineCap="round";g.lineJoin="round";if(a){g.beginPath();g.moveTo(a.x,a.y);g.lineTo(b.x,b.y);g.stroke()}else{g.beginPath();g.arc(b.x,b.y,12.5,0,Math.PI*2);g.fill()}g.restore();done[selectedKey]=false;scores[selectedKey]=null;lastPlan=null}
function nearestBeam(x,y){let k=-1,d0=1e9;beams.forEach((a,i)=>{const s=sourceFor(a),d=Math.hypot(x-s.x,y-s.y);if(d<d0){d0=d;k=i}});return d0<44?k:-1}
function angleAt(x,y){const b=bodyRing();return Math.atan2((y-b.cy)/b.ry,(x-b.cx)/b.rx)}function onRing(x,y){const b=bodyRing(),n=Math.sqrt(((x-b.cx)/b.rx)**2+((y-b.cy)/b.ry)**2);return n>.8&&n<1.23}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();const p=pt(e);if(role==="doctor"){if(!insideImage(p)){toast("Dibuja dentro de la CT.");return}drawing=true;lastPoint=p;stroke(null,p);canvas.setPointerCapture?.(e.pointerId);updateUI();draw();return}if(role==="physics"){if(!physicsUnlocked()){toast("Completa primero los contornos.");return}const n=nearestBeam(p.x,p.y);if(n>=0){dragBeam=n;canvas.setPointerCapture?.(e.pointerId);draw();return}if(onRing(p.x,p.y)){if(beams.length>=5){toast("Ya tienes 5 haces.");return}beams.push(angleAt(p.x,p.y));lastPlan=null;updateUI();draw()}else toast("Toca el aro punteado.")}});
canvas.addEventListener("pointermove",e=>{const p=pt(e);if(role==="doctor"&&drawing){e.preventDefault();if(insideImage(p)){stroke(lastPoint,p);lastPoint=p;draw()}}else if(role==="physics"&&dragBeam>=0){e.preventDefault();beams[dragBeam]=angleAt(p.x,p.y);lastPlan=null;updateUI();draw()}});
function stop(){drawing=false;lastPoint=null;dragBeam=-1;updateUI();draw()}canvas.addEventListener("pointerup",stop);canvas.addEventListener("pointercancel",stop);
function validate(){const s=S(selectedKey),data=layers[selectedKey].getContext("2d").getImageData(0,0,W,H).data;let pred=0,truth=0,inter=0;for(let y=Math.floor(imgRect.y);y<imgRect.y+imgRect.h;y+=5)for(let x=Math.floor(imgRect.x);x<imgRect.x+imgRect.w;x+=5){const p=data[(y*W+x)*4+3]>20,t=inStruct(s,x,y);if(p)pred++;if(t)truth++;if(p&&t)inter++}const dice=(pred+truth)?2*inter/(pred+truth):0;scores[selectedKey]=dice;if(dice>=.5){done[selectedKey]=true;toast("¡Buen contorno! Coincidencia educativa: "+Math.round(dice*100)+"%.")}else{done[selectedKey]=false;toast("Coincidencia "+Math.round(dice*100)+"%. Ajusta y vuelve a validar.")}if(complete()){role="physics";toast("¡Contorneo completo! Física médica desbloqueada.")}updateUI();draw()}
function clearContour(){layers[selectedKey].getContext("2d").clearRect(0,0,W,H);done[selectedKey]=false;scores[selectedKey]=null;lastPlan=null;updateUI();draw()}
function meanDose(s){let t=0,n=0;for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=11)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=11)if(inStruct(s,x,y)){t+=doseAt(x,y);n++}return n?t/n:0}
function healthyDose(){let t=0,n=0;for(let y=imgRect.y;y<imgRect.y+imgRect.h;y+=17)for(let x=imgRect.x;x<imgRect.x+imgRect.w;x+=17){if(structures.some(s=>inStruct(s,x,y)))continue;t+=doseAt(x,y);n++}return n?t/n:0}
function spread(){if(beams.length<2)return 0;const p=beams.slice().sort((a,b)=>a-b),g=[];for(let i=0;i<p.length;i++){const nx=i===p.length-1?p[0]+Math.PI*2:p[i+1];g.push(nx-p[i])}return clamp((Math.PI*1.35-Math.max(...g))/(Math.PI*.7),0,1)}
function evalPlan(){if(beams.length<3){toast("Necesitas al menos 3 haces.");return}const td=meanDose(S("target")),oars=structures.slice(1).map(s=>({label:s.label,dose:meanDose(s)})),healthy=healthyDose(),coverage=clamp(td/Math.max(1.7,beams.length*.56)*100,0,100),avg=oars.reduce((a,b)=>a+b.dose,0)/oars.length,score=Math.round(clamp(coverage-Math.max(0,avg-.45)*30-Math.max(0,healthy-.30)*18+spread()*9,0,100));lastPlan={coverage,oars,healthy,score};role="nurse";renderNurse();updateUI();draw();toast("Plan evaluado. Enfermería desbloqueada.")}
function renderNurse(){const list=document.getElementById("toxicityList");list.innerHTML="";nurseAnswers=Array(toxicities.length).fill(null);toxicities.forEach((q,i)=>{const d=document.createElement("div");d.className="tox-card";d.innerHTML=`<p><b>Situación ${i+1}.</b> ${q.q}</p><div class="tox-options"></div>`;const o=d.querySelector(".tox-options");[0,1,2,3].forEach(g=>{const b=document.createElement("button");b.textContent="Grado "+g;b.onclick=()=>{nurseAnswers[i]=g;[...o.children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected")};o.appendChild(b)});list.appendChild(d)});document.getElementById("nurseResult").classList.add("hidden")}
function evalNurse(){if(nurseAnswers.some(v=>v===null)){toast("Responde las tres situaciones.");return}let c=0;nurseAnswers.forEach((v,i)=>{if(v===toxicities[i].answer)c++});const r=document.getElementById("nurseResult");r.classList.remove("hidden");r.innerHTML=`<b>${c}/3 correctas.</b> ${c===3?"Excelente identificación de severidad.":"Revisa qué síntomas indican mayor intervención."}<br><small>Escala educativa simplificada; no sustituye CTCAE ni protocolos institucionales.</small>`;document.getElementById("nurseProgress").textContent=c===3?"Completado ✓":"Evaluado"}
function setRole(r){if(r==="physics"&&!physicsUnlocked()){toast("Completa los seis contornos para entrar a Física.");return}if(r==="nurse"&&!nurseUnlocked()){toast("Enfermería se desbloquea al evaluar el plan.");return}role=r;if(r==="nurse")renderNurse();updateUI();draw()}
function selector(){const w=document.getElementById("structureSelector");w.innerHTML="";structures.forEach(s=>{const b=document.createElement("button");b.className="structure-btn"+(s.key===selectedKey?" active":"")+(done[s.key]?" done":"");b.style.borderColor=rgba(s.color,.8);b.innerHTML=`<span style="color:${s.color}">●</span> ${s.label}`;b.onclick=()=>{selectedKey=s.key;updateUI();draw()};w.appendChild(b)})}
function renderStatus(){const box=document.getElementById("statusBox");box.innerHTML="";if(role==="doctor"){document.getElementById("missionNum").textContent="1";document.getElementById("missionTitle").textContent="Contorneo médico";document.getElementById("missionText").textContent="Selecciona una estructura, coloréala con el dedo y valida la coincidencia.";structures.forEach(s=>{const r=document.createElement("div");r.className="status-row";const sc=scores[s.key];r.innerHTML=`<span><i style="color:${s.color}">●</i> ${s.label}</span><b>${done[s.key]?"✓ "+Math.round(sc*100)+"%":sc==null?"Pendiente":Math.round(sc*100)+"% · ajustar"}</b>`;box.appendChild(r)})}else if(role==="physics"){document.getElementById("missionNum").textContent="2";document.getElementById("missionTitle").textContent="Planeación física";document.getElementById("missionText").textContent="Distribuye los haces para cubrir el tumor y reducir dosis a órganos sanos.";box.innerHTML='<div class="status-row"><span>Contornos médicos</span><b>Completos ✓</b></div>'}else{document.getElementById("missionNum").textContent="3";document.getElementById("missionTitle").textContent="Seguimiento de toxicidad";document.getElementById("missionText").textContent="Evalúa síntomas y reconoce cuándo aumenta su severidad.";box.innerHTML='<div class="status-row"><span>Plan</span><b>Evaluado ✓</b></div>'}}
function metrics(){const box=document.getElementById("metrics");box.innerHTML="";if(!lastPlan)return;const vals=[["Cobertura tumor",Math.round(lastPlan.coverage)+"%"],["Tejido sano",lastPlan.healthy.toFixed(2)],...lastPlan.oars.map(o=>[o.label,o.dose.toFixed(2)])];vals.forEach(([a,b])=>{const d=document.createElement("div");d.className="metric";d.innerHTML=`<span>${a}</span><b>${b}</b>`;box.appendChild(d)})}
function updateUI(){document.querySelectorAll(".role-tab").forEach(b=>{const r=b.dataset.role;b.classList.toggle("active",r===role);b.classList.toggle("locked",(r==="physics"&&!physicsUnlocked())||(r==="nurse"&&!nurseUnlocked()))});doctorToolbar.classList.toggle("hidden",role!=="doctor");canvasWrap.classList.toggle("hidden",role==="nurse");nursePanel.classList.toggle("hidden",role!=="nurse");document.getElementById("teacherPanel").classList.toggle("hidden",!teacher);document.getElementById("hudStage").textContent=role==="doctor"?"Doctora · contorneo":role==="physics"?"Física · planeación":"Enfermería · toxicidad";selector();renderStatus();document.getElementById("doctorProgress").textContent=complete()?"Completado ✓":structures.filter(s=>done[s.key]).length+"/6";document.getElementById("physicsProgress").textContent=!physicsUnlocked()?"Bloqueado":lastPlan?"Completado ✓":"Disponible";if(!nurseUnlocked())document.getElementById("nurseProgress").textContent="Bloqueado";document.getElementById("beamCount").textContent=beams.length+" / 5 haces";const chips=document.getElementById("beamChips");chips.innerHTML="";if(!beams.length){const c=document.createElement("span");c.className="beam-chip";c.textContent="Aún no hay haces";chips.appendChild(c)}else beams.forEach((a,i)=>{const c=document.createElement("span");c.className="beam-chip";c.textContent="Haz "+(i+1)+": "+Math.round((a*180/Math.PI+360)%360)+"°";chips.appendChild(c)});document.getElementById("undoBeamBtn").disabled=!beams.length||!physicsUnlocked();document.getElementById("resetBeamBtn").disabled=!beams.length;document.getElementById("evaluatePlanBtn").disabled=!physicsUnlocked()||beams.length<3;document.getElementById("score").textContent=lastPlan?lastPlan.score:"—";document.getElementById("meterFill").style.width=(lastPlan?lastPlan.score:0)+"%";let g="Completa primero el contorneo.";if(physicsUnlocked())g=beams.length<3?"Coloca al menos 3 haces.":"Listo para evaluar.";if(lastPlan)g=lastPlan.score>=85?"Excelente plan":lastPlan.score>=70?"Buen plan":lastPlan.score>=55?"Plan mejorable":"Replantea los ángulos";document.getElementById("grade").textContent=g;metrics();const pr=document.getElementById("planResult");if(lastPlan){pr.classList.remove("hidden");pr.textContent=lastPlan.score>=85?"Muy buena cobertura con exposición reducida de órganos a riesgo.":lastPlan.score>=70?"Buen equilibrio; todavía puedes proteger mejor algún órgano.":"Prueba ángulos más separados y evita trayectorias que crucen el corazón."}else pr.classList.add("hidden")}
document.querySelectorAll(".role-tab").forEach(b=>b.onclick=()=>setRole(b.dataset.role));document.getElementById("validateContourBtn").onclick=validate;document.getElementById("clearContourBtn").onclick=clearContour;document.getElementById("undoBeamBtn").onclick=()=>{beams.pop();lastPlan=null;updateUI();draw()};document.getElementById("resetBeamBtn").onclick=()=>{beams=[];lastPlan=null;updateUI();draw();toast("Haces reiniciados.")};document.getElementById("evaluatePlanBtn").onclick=evalPlan;document.getElementById("hintBtn").onclick=()=>toast(role==="doctor"?"Pinta toda la silueta de la estructura, no solo un punto.":"En mama izquierda suele ser clave vigilar corazón y pulmón ipsilateral.");document.getElementById("evaluateNurseBtn").onclick=evalNurse;
document.getElementById("teacherBtn").onclick=()=>{if(teacher){teacher=false;showTruth=false;document.getElementById("showTruthChk").checked=false;updateUI();draw();toast("Modo profesor desactivado.")}else document.getElementById("teacherModal").classList.remove("hidden")};document.getElementById("teacherCancelBtn").onclick=()=>document.getElementById("teacherModal").classList.add("hidden");document.getElementById("teacherLoginBtn").onclick=()=>{const u=document.getElementById("teacherUser").value.trim(),p=document.getElementById("teacherPass").value;if(u==="Curie"&&p==="Iridio"){teacher=true;document.getElementById("teacherModal").classList.add("hidden");updateUI();draw();toast("Modo profesor activado.")}else toast("Credenciales incorrectas.")};document.getElementById("showTruthChk").onchange=e=>{showTruth=e.target.checked;draw()};
document.querySelectorAll(".shift-btn").forEach(b=>b.onclick=()=>{const s=S(selectedKey),dx=parseFloat(b.dataset.dx)/imgRect.w,dy=parseFloat(b.dataset.dy)/imgRect.h;s.shapes.forEach(sh=>{sh.x+=dx;sh.y+=dy});draw()});document.querySelectorAll(".scale-btn").forEach(b=>b.onclick=()=>{const f=parseFloat(b.dataset.scale),s=S(selectedKey),cx=s.shapes.reduce((a,x)=>a+x.x,0)/s.shapes.length,cy=s.shapes.reduce((a,x)=>a+x.y,0)/s.shapes.length;s.shapes.forEach(sh=>{sh.x=cx+(sh.x-cx)*f;sh.y=cy+(sh.y-cy)*f;if(sh.type==="circle")sh.r*=f;else{sh.rx*=f;sh.ry*=f}});draw()});document.getElementById("saveTeacherBtn").onclick=()=>{localStorage.setItem("misionRT_breast_truth_v03",JSON.stringify(structures));toast("Referencias guardadas en este dispositivo.")};document.getElementById("resetTeacherBtn").onclick=()=>{structures=JSON.parse(JSON.stringify(DEFAULT_STRUCTURES));localStorage.removeItem("misionRT_breast_truth_v03");selectedKey="target";updateUI();draw();toast("Referencias restauradas.")};
updateImgRect();updateUI();draw();
})();